# Generated by Django 4.2.14 on 2024-07-17 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=20)),
                ('distance_miles', models.FloatField()),
                ('moving_time', models.FloatField()),
                ('average_heartrate', models.FloatField(blank=True, null=True)),
                ('max_heartrate', models.FloatField(blank=True, null=True)),
                ('calories', models.FloatField(default=0)),
                ('type_effort', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
